# Generated by Django 5.0.7 on 2024-09-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_no',
        ),
        migrations.AddField(
            model_name='account',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=12),
        ),
    ]
